Bump go version to 1.22, bump linter
sigstore/rekor-monitor pull request #358
Opened 2024-03-11 23:49 UTC by haydentherapper

#### Summary

#### Release Note

#### Documentation

2024-03-12 00:06 UTC, haydentherapper commented
For some reason, codeql is downloading 2.16.3 rather than 2.16.4 which includes go 1.22. will hold off for now

2024-03-12 18:46 UTC, cpanato submitted a review, later dismissed
besides the codeql
lgtm

2024-03-12 19:00 UTC, haydentherapper commented
Nothing to do at this point, codeql is being pulled from the hosted tool cache, so we just need to wait for that to be updated.

2024-03-13 22:14 UTC, haydentherapper commented
Toolchain now contains 2.16.4 but Go 1.22 support is still missing even though the docs say it should be present. will wait til 2.16.5 i guess

2024-04-08 23:17 UTC, haydentherapper commented
@cpanato finally figured it out, I sent the go.mod go version to the specific version of Go because apparently go 1.22 is a development version. hopefully this is correct now

2024-04-09 07:52 UTC, cpanato requested changes
thanks! some small cr

2024-04-09 07:52 UTC, cpanato commented on .github/workflows/verify.yml
> +          version: v1.56
can you update to `v1.57` ?

2024-04-09 07:52 UTC, cpanato commented on .github/workflows/verify.yml
>          uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3
as you are here can you update the version comment to the full semver as well?

2024-04-09 17:07 UTC, haydentherapper commented on .github/workflows/verify.yml
> +          version: v1.56
done

2024-04-09 17:48 UTC, cpanato commented on .github/workflows/verify.yml
> +          version: v1.56
thanks!

2024-04-09 17:49 UTC, cpanato approved these changes

2024-04-09 17:49 UTC, merged