Database log streamlined
sigstore/rekor-monitor pull request #38
Opened 2022-03-22 01:49 UTC by vivek42537

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-03-22 21:19 UTC, SantiagoTorres requested changes
Happy to see progress! I left a couple of comments. Let's start with removing the unneeded files first!

2022-03-22 21:19 UTC, SantiagoTorres commented on cmd/mirroring/logInfo.txt
> +1528952 e0a8822e61ba905c6efb216666c3e09f37f403c5d1f55e8cef8d964ddddefabf
can you remove tihs file from the PR?

2022-03-22 21:19 UTC, SantiagoTorres commented on cmd/mirroring/logInfo.txt
> +1528952 e0a8822e61ba905c6efb216666c3e09f37f403c5d1f55e8cef8d964ddddefabf
and the .DS_Store's above. These are apple thumbnails that shouldn't be checked into the repo

2022-03-22 21:19 UTC, SantiagoTorres commented on cmd/mirroring/main.go
> +}
Not sure if we need the structs above, do we?

2022-03-22 21:19 UTC, SantiagoTorres commented on cmd/mirroring/main.go
> +				// b, _ := base64.StdEncoding.DecodeString(pay)
can you remove the commented code in this block?

2022-03-22 21:19 UTC, SantiagoTorres commented on go.mod
> +	github.com/mattn/go-sqlite3 v1.14.11 // indirect
we probably don't need any of the *.db's above, can you remove them?

2022-03-22 21:19 UTC, SantiagoTorres commented on mirroring/database.go
> +	statement, err := database.Exec("CREATE TABLE entries (idx INTEGER PRIMARY KEY NOT NULL, payload TEXT)") //sql query string (if no db)
can you move the comment to a separate line?

2022-03-22 21:19 UTC, SantiagoTorres commented on mirroring/database_test.go
> +    }
we probably need to run gofmt on this file.

2022-10-04 16:53 UTC, haydentherapper commented
Closing older PRs, feel free to reopen if you want to continue this work.

2022-10-04 16:53 UTC, closed without merging