Refactor CT log monitor to support monitoring certificate identities
sigstore/rekor-monitor pull request #534
Opened 2024-11-13 23:07 UTC by linus-sun

#### Summary

Per changes outlined in [this doc](https://docs.google.com/document/d/1fdO5jMTJOtMhIWs_lzWlb25olIWMvYix8LW7ugeMH8k/edit?tab=t.0#heading=h.xgjl2srtytjt), this PR implements support for scanning certificate identities and matching values within a certificate transparency log. A certificate can be matched on via its certificate subject and optionally additional issuers.

This PR depends on #527 

#### Release Note

#### Documentation

2024-11-14 23:22 UTC, mihaimaruseac submitted a review, later dismissed

2024-11-18 19:09 UTC, haydentherapper commented
LGTM pending 527.

2024-11-19 01:48 UTC, mihaimaruseac approved these changes

2024-11-19 20:36 UTC, haydentherapper requested changes

2024-11-19 20:53 UTC, linus-sun commented on pkg/ct/monitor.go
> +	certIssuer := logEntry.X509Cert.Issuer.String()
Will do- I believe this will require another case of code duplication for CertMatchesPolicy

2024-11-20 00:05 UTC, haydentherapper commented on pkg/ct/monitor.go
> +	certIssuer := logEntry.X509Cert.Issuer.String()
Looks like we still need to call `CertMatchesPolicy` from here

2024-11-20 00:45 UTC, haydentherapper approved these changes

2024-11-20 00:48 UTC, haydentherapper approved these changes

2024-11-20 00:48 UTC, merged